### ISSUE TITLE
Analysis TODO

### ISSUE THREAD

**Issue by hainest** [buildsi/splice-experiment-results#13]
- [x] TODO why does number changed go up?

  - Just variance. No real reason.

- [x] TODO TIM cross correlate 41 two predictor cases against the _chk cases found. When symbols says not compatible and libabigail says they are - what percentage are these _chk cases?
  - I'm working on this now

- [x] TODO TIM THIS MANY Libabigail fails to report any reason for the incompatibility (e.g., the return value is non-zero without terminal output). TIM WHEREVER THIS GOES MAKE SURE TO ADD THAT WE FILTER LIBABIGAIL CASES - something something percentages don’t add up?
  - This has been accounted for by including all cases where the predictors disagree

- [x] TODO TIM unique count of these to look at disjoint sets.
  - Results for this were added in https://github.com/buildsi/splice-experiment-results/pull/11

- [x] TODO some report on function changes/adds/removes
  - Results for this were added in https://github.com/buildsi/splice-experiment-results/pull/11

- [x] abi laboratory cases that fail with message "ERROR\: can't find debug info in object" should be excluded from analysis.

---
Items to add to report:

- [x] Results from 2,3,4,5

- [x] Output from 'agreement.py'

libabigail incompatibilities for changes in
- [x] vtable
- [x] enumerator
- [x] ?? (Ben said he'd get me a list)
